export const SET_MOUNTED = 'SET_MOUNTED';
export const UPDATE_UNSEEN_COUNTS = 'UPDATE_UNSEEN_COUNTS';
export const UPDATE_MOST_RECENT_SEEN_LOCAL = 'UPDATE_MOST_RECENT_SEEN_LOCAL';
export const UPDATE_MOST_RECENT_SEEN_REQUEST = 'UPDATE_MOST_RECENT_SEEN_REQUEST';
export const UPDATE_MOST_RECENT_SEEN_SUCCESS = 'UPDATE_MOST_RECENT_SEEN_SUCCESS';
export const UPDATE_MOST_RECENT_SEEN_FAILURE = 'UPDATE_MOST_RECENT_SEEN_FAILURE';